<?php
function allCrea(){
    $creations = [
        [
            'name' => 'AsterZKalhan',
            'suffixe' => 'Asterz',
            'realisation' => 'Création d\'un logo, d\'overlays twitch ainsi qu\'un pannel d\'alertes et bannières ',
            'picture' => 'logoAsterz.png',
            'picture1' => 'logoAsterz.png',
            'picture2' => 'overlay1asterz.png',
            'picture3' => 'overlay2asterz.png',
            'picture4' => 'bannerasterz.png',
            'framworks' => '<i class="fab fa-buysellads fa-2x p-3"></i>',
            'url' => 'https://www.twitch.tv/asterzkalhan',
        ],
        [
            'name' => 'Lapins Perdus Of Azeroth',
            'suffixe' => 'LPOA',
            'realisation' => 'un site, création d\'identité visuelle, des bannieres discord',
            'picture' => 'lpoa.png',
            'picture1' => 'lpoa.png',
            'picture2' => 'bannièrelpoa.png',
            'picture3' => 'prixraids.png',
            'picture4' => '',
            'framworks' => '<i class="fab fa-wordpress fa-2x p-3" ></i><i class="fab fa-html5 fa-2x p-3" ></i >',
            'url' => 'https://lpoa.nvg-tv.com/',
        ],
        [
            'name' => 'Normandie Viking Gaming',
            'suffixe' => 'NVG',
            'realisation' => 'un site, des maquettes, une charte graphique',
            'picture' => 'nvg.png',
            'picture1' => 'nvg.png',
            'picture2' => 'maquette_site_2.0.1.png',
            'picture3' => 'partenaires.png',
            'picture4' => 'menu.png',
            'framworks' => '<i class="fab fa-wordpress fa-2x p-3"></i><i class="fab fa-html5 fa-2x p-3"></i><i class="fab fa-js fa-2x p-3"></i><i class="fab fa-buysellads fa-2x p-3"></i>',
            'url' => 'https://nvg-tv.com/',
        ],
        [
            'name' => 'Les créas de Caro',
            'suffixe' => 'Caro',
            'realisation' => 'un logo, un mockup d\'une bannière facebook',
            'picture' => 'logo_caro3.png',
            'picture1' => 'logo_caro3.png',
            'picture2' => 'banner_caro.png',
            'picture3' => 'pagefb_caro.png',
            'picture4' => '',
            'framworks' => '<i class="fab fa-buysellads fa-2x p-3"></i>',
            'url' => 'https://www.facebook.com/Les-Cr%C3%A9as-de-Caro-1423384494609517/',
        ],
        [
            'name' => 'E.D.S',
            'suffixe' => 'EDS',
            'realisation' => '3 bannières youtube',
            'picture' => 'bannereds.png',
            'picture1' => 'bannereds.png',
            'picture2' => 'bannièrebasic.png',
            'picture3' => 'bannière-sound.png',
            'picture4' => '',
            'framworks' => '<i class="fab fa-buysellads fa-2x p-3"></i>',
            'url' => '',
        ],
        [
            'name' => 'Elevage Canin REA',
            'suffixe' => 'REA',
            'realisation' => 'Refonte de site, Responsive',
            'picture' => 'elevagecanin.png',
            'picture1' => 'images/rea1.jpg',
            'picture2' => 'images/rea2.jpg',
            'picture3' => '',
            'picture4' => '',
            'framworks' => '<i class="fab fa-html5 fa-2x p-3"></i><i class="fab fa-buysellads fa-2x p-3"></i>',
            'url' => '',
        ],
        [
            'name' => 'Notmine',
            'suffixe' => 'Notmine',
            'realisation' => 'Logotipage, Maquetting',
            'picture' => 'notmine.png',
            'picture1' => 'mockupNotmine.png',
            'picture2' => 'maquette_notmine_cloe.png',
            'picture3' => 'maquette_notmine_tel.png',
            'picture4' => 'logoNotmine.png',
            'framworks' => '<i class="fab fa-html5 fa-2x p-3"></i> <i class="fab fa-buysellads fa-2x p-3"></i>',
            'url' => '',
        ],
        [
            'name' => 'Conquerant Conseil',
            'suffixe' => 'Conquerant',
            'realisation' => 'Logotipage, Affiche, Flyer, Bannière',
            'picture' => 'conquerant.png',
            'picture1' => 'affiche.png',
            'picture2' => 'visitcardconquerant.png',
            'picture3' => 'banniere_conquerant.png',
            'picture4' => '',
            'framworks' => '<i class="fab fa-buysellads fa-2x p-3"></i>',
            'url' => '',
        ],
        [
            'name' => 'KuroeDesign',
            'suffixe' => 'K',
            'realisation' => 'création d\'identité visuelle, maquettes de site',
            'picture' => 'logoKuroe.png',
            'picture1' => 'logoKuroe.png',
            'picture2' => 'logo_kuroe2.png',
            'picture3' => 'charteKuroe.png',
            'picture4' => '',
            'framworks' => '<i class="fab fa-buysellads fa-2x p-3"></i>',
            'url' => '',
        ],
    ];
    return $creations;
}

?>